# Generated by Django 2.2 on 2020-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_feedback_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
