# Generated by Django 2.2 on 2020-07-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_feedback_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='attendance_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
