# Generated by Django 2.2 on 2020-07-30 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_feedback_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
