# Generated by Django 2.2 on 2020-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_batch_batch_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
