# Generated by Django 2.2 on 2020-08-01 19:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_batch_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='notice',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
